spring:
  #redis配置
  redis:
    host: localhost
    port: 6379
  #数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/diploma?serverTimezone=UTC&useUbcode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
#mybatis配置
mybatis:
  type-aliases-package: com.qrsx.login.model,;com.qrsx.commence.model
  mapper-locations: classpath:mapping/login/*.xml,classpath:mapping/commence/*.xml
