spring:
  #redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  #数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=UTC&useUbcode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/admin/*/*.xml,classpath:mapping/commence/*.xml
  type-aliases-package: com.qrsx.commence.data,;com.qrsx.admin.*.data
  configuration:
    map-underscore-to-camel-case: true
    mapper:
      mappers: com.gogle.mgt.dataaccess.mybatis.TkMapper #通用基类配置
      identity: MYSQL
#配置端口号
server:
  port: 10012
